version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    groups:
      ruby-minor-and-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
