export const AUTH_SET = Symbol();

export const VISIBLE_PANES_ADD = 'VISIBLE_PANES_ADD';
export const VISIBLE_PANES_REMOVE = 'VISIBLE_PANES_REMOVE';
export const VISIBLE_PANES_SET = 'VISIBLE_PANES_SET';
