export const AUTH_SET = Symbol();

export const DISTRACTION_FREE_ENTER = 'DISTRACTION_FREE_ENTER';
export const DISTRACTION_FREE_LEAVE = 'DISTRACTION_FREE_LEAVE';
export const TAG_DRAWER_HIDE = 'TAG_DRAWER_HIDE';
export const TAG_DRAWER_SHOW = 'TAG_DRAWER_SHOW';
