name: 'Deploy Simplenote'
description: 'Builds and deploys Simplenote to VIP Go branches'
branding:
  icon: 'truck'
  color: 'green'
inputs:
  APP_ID:
    description: 'Application ID'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub Token'
    requried: true
  BRANCH:
    description: 'Branch'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: './.github/actions/deploy/entrypoint.sh'
  env:
    APP_ID: ${{ inputs.APP_ID }}
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    BRANCH: ${{ inputs.BRANCH }}
